[project]
name = "qtype"
version = "0.1.0"
description = "DSL for Generative AI Prototyping"
authors = [{ name="Lou Kratz", email="qtype@lou.dev" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jsonschema>=4.24.0",
    "pydantic>=2.11.5",
    "pyyaml>=6.0.2",
]

[tool.setuptools.packages.find]
include = ["qtype", "scripts"]

[project.scripts]
qtype-validate = "scripts.validate:main"
