
name: Test UI
description: QType UI tests

runs:
  using: composite
  steps:
    - name: Run UI unit tests
      run: |
        cd ui 
        npm run test
      shell: bash
    - name: Job success
      if: success ()
      run: echo 'QType UI tests successful 🎉' >> $GITHUB_STEP_SUMMARY
      shell: bash
    - name: Job failure
      if: failure ()
      run: echo 'QType UI tests unsuccessful 😱' >> $GITHUB_STEP_SUMMARY
      shell: bash