# This workflow publishes the package to Test PyPI on merge to main
name: Publish to Test PyPI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to Test PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for trusted publishing
    environment:
      name: pypi
      url: https://pypi.org/p/qtype
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Build package
        run: |
          uv build

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
